#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0 using LevelOfTheory(method='b97d3',basis='def2msvp',software='gaussian').
"""
autoGenerated=True
entry(
    index = 0,
    label = "CF3CF2COOH <=> CF3COOH + CF2",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.60257e+11,'s^-1'), n=0.632222, Ea=(356.377,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.26589, dn = +|- 0.0311892, dEa = +|- 0.163022 kJ/mol"""),
)

entry(
    index = 1,
    label = "CF3CF2COOH <=> CF3CF2OH + CO",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(3.51823e+10,'s^-1'), n=0.993072, Ea=(443.169,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.50298, dn = +|- 0.0538988, dEa = +|- 0.281723 kJ/mol"""),
)

entry(
    index = 2,
    label = "CF3CF2COOH <=> CF3CF + FCOOH",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.68437e+11,'s^-1'), n=0.675115, Ea=(368.78,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.33509, dn = +|- 0.0382303, dEa = +|- 0.199826 kJ/mol"""),
)

entry(
    index = 3,
    label = "CF3CF2COOH <=> CFCOOH + CF4",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.07109e+11,'s^-1'), n=0.67772, Ea=(511.905,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.28469, dn = +|- 0.0331393, dEa = +|- 0.173215 kJ/mol"""),
)

entry(
    index = 4,
    label = "CF3CF2COOH <=> CF3CF2H + CO2",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(5.64505e+11,'s^-1'), n=0.764701, Ea=(305.601,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.16915, dn = +|- 0.0206728, dEa = +|- 0.108054 kJ/mol"""),
)

entry(
    index = 5,
    label = "CF3CF2COOH <=> CF2CO + CF3OH",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.04324e+11,'s^-1'), n=0.709345, Ea=(534.759,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.30891, dn = +|- 0.0356098, dEa = +|- 0.186129 kJ/mol"""),
)

