#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0 using LevelOfTheory(method='b97d3',basis='def2msvp',software='gaussian').
"""
autoGenerated=True
entry(
    index = 0,
    label = "CF3CF2COOH <=> CF3COOH + CF2",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.63748e+13,'s^-1'), n=0, Ea=(359.537,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.05212, dn = +|- 0, dEa = +|- 0.20108 kJ/mol"""),
)

entry(
    index = 1,
    label = "CF3CF2COOH <=> CF3CF + FCOOH",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.63748e+13,'s^-1'), n=0, Ea=(359.537,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.05212, dn = +|- 0, dEa = +|- 0.20108 kJ/mol"""),
)

entry(
    index = 2,
    label = "CF3CF2COOH <=> CFCOOH + CF4",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.63748e+13,'s^-1'), n=0, Ea=(359.537,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.05212, dn = +|- 0, dEa = +|- 0.20108 kJ/mol"""),
)

entry(
    index = 3,
    label = "CF3CF2COOH <=> CF3CF2OH + CO",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.3835e+13,'s^-1'), n=0, Ea=(372.153,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.05616, dn = +|- 0, dEa = +|- 0.216243 kJ/mol"""),
)

entry(
    index = 4,
    label = "CF3CF2COOH <=> CFCOOH + CF4",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.97622e+13,'s^-1'), n=0, Ea=(515.297,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.05592, dn = +|- 0, dEa = +|- 0.215348 kJ/mol"""),
)

entry(
    index = 5,
    label = "CF3CF2COOH <=> CF3CF2OH + CO",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(6.10312e+13,'s^-1'), n=0, Ea=(445.887,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.08708, dn = +|- 0, dEa = +|- 0.330478 kJ/mol"""),
)

entry(
    index = 6,
    label = "CF3CF2COOH <=> CF2HCF3 + CO2",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.69222e+14,'s^-1'), n=0, Ea=(309.419,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""FitWted to 20 data points; dA = *|/ 1.06255, dn = +|- 0, dEa = +|- 0.240147 kJ/mol"""),
)

