#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0 using LevelOfTheory(method='b97d3',basis='def2msvp',software='gaussian').
"""
autoGenerated=True
entry(
    index = 0,
    label = "2003846667223680600001 <=> 1001482381140000000001 + 1002122340540000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.27984e+12,'s^-1'), n=0.461433, Ea=(384.354,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.21022, dn = +|- 0.0252399, dEa = +|- 0.131926 kJ/mol"""),
)

entry(
    index = 1,
    label = "2003846667223680600001 <=> 1001482381140000000001 + 1002122340540000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.27984e+12,'s^-1'), n=0.461433, Ea=(384.354,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.21022, dn = +|- 0.0252399, dEa = +|- 0.131926 kJ/mol"""),
)

entry(
    index = 2,
    label = "2003846667223680600001 <=> 1502984803620600000001 + 500620380000000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(6.91038e+11,'s^-1'), n=0.730625, Ea=(492.116,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.35408, dn = +|- 0.0400982, dEa = +|- 0.209589 kJ/mol"""),
)

entry(
    index = 3,
    label = "2003846667223680600001 <=> 1502823922432230600001 + 500620380000000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(8.31302e+11,'s^-1'), n=0.670671, Ea=(450.192,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.26841, dn = +|- 0.0314529, dEa = +|- 0.164401 kJ/mol"""),
)

entry(
    index = 4,
    label = "2003846667223680600001 <=> 1803646687765942100001 + 200200000000000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.42207e+12,'s^-1'), n=0.50898, Ea=(259.898,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.28395, dn = +|- 0.0330632, dEa = +|- 0.172817 kJ/mol"""),
)

entry(
    index = 5,
    label = "2003846667223680600001 <=> 1001482001520000000001 + 1002122340540000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.5327e+12,'s^-1'), n=0.476319, Ea=(435.907,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.28197, dn = +|- 0.0328594, dEa = +|- 0.171752 kJ/mol"""),
)

