#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0 using LevelOfTheory(method='b97d3',basis='def2msvp',software='gaussian').
"""
autoGenerated=True
entry(
    index = 0,
    label = "941421881400000000001_R1 <=> 280280000000000000001 + 660901080000000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(9.58237e+11,'s^-1'), n=0.502922, Ea=(193.8,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.26915, dn = +|- 0.03153, dEa = +|- 0.164804 kJ/mol"""),
)

entry(
    index = 1,
    label = "941421881400000000001_R2 <=> 941461610900730000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.19454e+12,'s^-1'), n=0.339155, Ea=(287.004,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.09351, dn = +|- 0.0118258, dEa = +|- 0.0618119 kJ/mol"""),
)

entry(
    index = 2,
    label = "941421881400000000001_R3 <=> 280280000000000000001 + 660901080000000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(9.59562e+11,'s^-1'), n=0.50263, Ea=(193.806,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.26899, dn = +|- 0.0315134, dEa = +|- 0.164717 kJ/mol"""),
)

entry(
    index = 3,
    label = "941421881400000000001_R4 <=> 941742762340700000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.17923e+11,'s^-1'), n=0.666721, Ea=(725.237,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.14771, dn = +|- 0.0182252, dEa = +|- 0.0952611 kJ/mol"""),
)

