#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0 using LevelOfTheory(method='b97d3',basis='def2msvp',software='gaussian').
"""
autoGenerated=True
entry(
    index = 0,
    label = "C2F5SO3H <=> CF3C_radical + FSO3H",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.17518e+13,'s^-1'), n=0, Ea=(386.692,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.03773, dn = +|- 0, dEa = +|- 0.146573 kJ/mol"""),
)

entry(
    index = 2,
    label = "C2F5SO3H <=> CF3SO3H + CF2_radical",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.7218e+14,'s^-1'), n=0, Ea=(495.819,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.0604, dn = +|- 0, dEa = +|- 0.232119 kJ/mol"""),
)

entry(
    index = 3,
    label = "C2F5SO3H <=> CF3SOH + CF2_radical",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.317e+14,'s^-1'), n=0, Ea=(453.591,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.05494, dn = +|- 0, dEa = +|- 0.211666 kJ/mol"""),
)

entry(
    index = 4,
    label = "C2F5SO3H <=> CF3_cyclic_SO3 + HF",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.06586e+14,'s^-1'), n=0, Ea=(262.477,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.04212, dn = +|- 0, dEa = +|- 0.163274 kJ/mol"""),
)

entry(
    index = 5,
    label = "C2F5SO3H <=> C2F4 + FSO3H",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(5.59502e+13,'s^-1'), n=0, Ea=(438.321,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.03953, dn = +|- 0, dEa = +|- 0.153449 kJ/mol"""),
)

