#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0 using LevelOfTheory(method='b97d3',basis='def2msvp',software='gaussian').
"""
autoGenerated=True
entry(
    index = 0,
    label = "CF3COOH <=> CO2 + CHF3",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(5.03864e+11,'s^-1'), n=0.769124, Ea=(311.842,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.16911, dn = +|- 0.0206684, dEa = +|- 0.108031 kJ/mol"""),
)

