#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0 using LevelOfTheory(method='b97d3',basis='def2msvp',software='gaussian').
"""
autoGenerated=True
entry(
    index = 0,
    label = "1502984803620600000001 <=> 1001961801040200000001 + 500620380000000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.20636e+12,'s^-1'), n=0.857894, Ea=(677.037,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.43279, dn = +|- 0.0475723, dEa = +|- 0.248655 kJ/mol"""),
)

