#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0 using LevelOfTheory(method='b97d3',basis='def2msvp',software='gaussian').
"""
autoGenerated=True
entry(
    index = 0,
    label = "1141903082400600000001 <=> 280280000000000000001 + 861382320600000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(9.56803e+10,'s^-1'), n=1.0281, Ea=(451.255,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.51962, dn = +|- 0.0553553, dEa = +|- 0.289336 kJ/mol"""),
)

entry(
    index = 1,
    label = "1141903082400600000001 <=> 280280000000000000001 + 861382320600000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(9.56803e+10,'s^-1'), n=1.0281, Ea=(451.255,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.51962, dn = +|- 0.0553553, dEa = +|- 0.289336 kJ/mol"""),
)

entry(
    index = 2,
    label = "1141903082400600000001 <=> 440560320000000000001 + 701061740000000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.34073e+11,'s^-1'), n=0.768057, Ea=(306.941,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.17254, dn = +|- 0.0210563, dEa = +|- 0.110059 kJ/mol"""),
)

