#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0 using LevelOfTheory(method='b97d3',basis='def2msvp',software='gaussian').
"""
autoGenerated=True
entry(
    index = 0,
    label = "661381981260000000001 <=> 140260020000000000003 + 520881200000000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.01498e+10,'s^-1'), n=1.08743, Ea=(512.896,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.52538, dn = +|- 0.055856, dEa = +|- 0.291953 kJ/mol"""),
)

entry(
    index = 1,
    label = "661381981260000000001 <=> 200200000000000000001 + 460940920440000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.57338e+10,'s^-1'), n=1.35484, Ea=(321.512,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.37691, dn = +|- 0.0423105, dEa = +|- 0.221152 kJ/mol"""),
)

entry(
    index = 2,
    label = "661381981260000000001 <=> 320440200000000000001 + 340700660000000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.67826e+11,'s^-1'), n=0.982757, Ea=(405.405,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.28625, dn = +|- 0.0333001, dEa = +|- 0.174056 kJ/mol"""),
)

entry(
    index = 3,
    label = "661381981260000000001 <=> 20020000000000000001 + 641121280800000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.46824e+09,'s^-1'), n=1.41493, Ea=(489.339,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.24705, dn = +|- 0.0292054, dEa = +|- 0.152654 kJ/mol"""),
)

entry(
    index = 4,
    label = "661381981260000000001 <=> 20020000000000000001 + 641121300780000000001",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(9.1304e+08,'s^-1'), n=1.67398, Ea=(397.262,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.49902, dn = +|- 0.0535506, dEa = +|- 0.279903 kJ/mol"""),
)

