#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0 using LevelOfTheory(method='b97d3',basis='def2msvp',software='gaussian').
"""
autoGenerated=True
entry(
    index = 0,
    label = "CF3COOH <=> CO2 + CHF3",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.67909e+14,'s^-1'), n=0, Ea=(315.74,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Fitted to 20 data points; dA = *|/ 1.06246, dn = +|- 0, dEa = +|- 0.239783 kJ/mol"""),
)

