#!/bin/bash
#SBATCH --account="punim0131"
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=3-00:00:00
#SBATCH --mem=32G
#SBATCH --partition=sapphire
#SBATCH --job-name=kinbot_propyl
#SBATCH --output=kinbot_%j.log

# Load required modules
module purge
module load NVHPC/22.11-CUDA-11.7.0
module load Gaussian/g16c01-CUDA-11.7.0
module load Python/3.10.4
module load Anaconda3/2024.02-1

# adding additinal modules
#virtualenv ~/venvs/venv-3.10.4
#source ~/venvs/venv-3.10.4/bin/activate

# Initialize conda
eval "$(conda shell.bash hook)"

# Activate KinBot environment
conda activate kinbot-env


python 2003846667223680600001_r12_insertion_R_9_1_2_IRC_R.py 
